name: dcd
version: 0.12.0
summary: Auto-completion service for the D programming language
description: |
  The D Completion Daemon (DCD) provides auto-completion support
  for the D programming language via a simple client-server setup.
  The dcd-client app can be used to connect text editors and IDEs
  to the auto-completion service, while dcd-server provides the
  underlying service daemon.
confinement: classic
grade: stable

apps:
  dcd-client:
    command: env XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR%/*}" $SNAP/bin/dcd-client
  dcd-server:
    command: env XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR%/*}" $SNAP/bin/dcd-server

parts:
  dcd:
    source: https://github.com/dlang-community/DCD.git
    source-tag: v0.12.0
    source-type: git
    plugin: make
    makefile: makefile
    make-parameters:
      - DMD=/snap/bin/dmd
    artifacts:
      - bin/dcd-server
      - bin/dcd-client
    build-snaps:
    - dmd
    build-packages:
    - build-essential
