name: dcd
version: 0.11.1
summary: An auto-complete program for the D programming language
description: |
    The D Completion Daemon, is a cross platform auto-complete 
    service for the D programming language. 
    It's used by several text editors and IDE to get IDE-grade features.
confinement: classic
grade: stable

apps:
  dcd-client:
    command: env XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR%/*}" bin/dcd-client
    aliases: [dcd-client]
  dcd-server:
    command: env XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR%/*}" bin/dcd-server
    aliases: [dcd-server]

parts:
  dcd:
    source: https://github.com/dlang-community/DCD.git
    source-tag: v0.11.1
    source-type: git
    plugin: make
    makefile: makefile
    make-parameters:
      - DMD=/snap/bin/dmd
    artifacts:
      - bin/dcd-server
      - bin/dcd-client
    build-snaps:
    - dmd
    build-packages:
    - build-essential
